### ISSUE TITLE
JACK support?

### ISSUE THREAD

**Issue by mxmilkiib** [eclab/flow#2]
[JACK](https://jackaudio.org) supports inter-app [patching](https://community.vcvrack.com/uploads/default/original/2X/b/bddca50d726554bcec1fbcb58befe23180c3b9c9.png) of audio, MIDI and [CV](https://linuxmusicians.com/viewtopic.php?f=1&t=20701). Might JACK support in Flow be a thing some day?

**Comment by eclab** [comment]
Would love to reduce latency!  Flow is presently entirely dependent on java.audio; I don't expect that it'll support Jack via a separate interface, though (IIRC) Jack already provides some underlying services for java.audio at least on Linux.

Another issue is cross-platform support.  Jack is (or was until recently) seriously broken on OSX: its installation breaks Java audio apps entirely (!) and its installer is further broken such that you can't uninstall it, so once you install Jack on OSX, good bye Java audio.  :-(  So not sure what to do there.
